# do not touch this line
configVersion: 2

description: App to verify babies conditions on maternities.
keywords: 'face, temperature, humidity, leds, push'
name: maternitySentinel
displayName: Maternity Sentinel

services:
  maternitySentinel:
    engine: detection
    type: demographics