# do not touch this line
configVersion: 2

description: App to verify babies conditions on maternities.
keywords: 'face, temperature, humidity, leds, push'
name: maternity-sentinel
displayName: Maternity Sentinel

services:
  maternity-sentinel:
    engine: detection
    type: demographics

sensors:
  - temperature
  - humidity
